site_name: Santiago Bassani - Levensworth

theme:  
  name: material  
  custom_dir: overrides
  
  palette:
    primary: 'indigo'
    accent: 'indigo'

  features:    
    - navigation.tabs
    - navigation.indexes

nav:
  - About me: index.md
  - Projects: projects.md
  - CV: santiago_bassani_CV.pdf
  - Blog:   
    - blog/index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/levensworth
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/santiago-bassani/
    - icon: fontawesome/brands/twitter
      link: https://x.com/_levensworth

extra_css:
  - css/custom.css

plugins:
  - blog